<a href="https://colab.research.google.com/github/Miliseff/hackaton/blob/main/hack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib
import xlrd as xlrd  #leer archivos exel
import gdown #descarga desde la pag

In [8]:

import gdown
FILE_URL = 'https://api.worldbank.org/v2/es/indicator/SM.POP.NETM?downloadformat=excel'

filename = 'migra.xls'
gdown.download(FILE_URL, filename, quiet=False)
print(filename)

Downloading...
From: https://api.worldbank.org/v2/es/indicator/SM.POP.NETM?downloadformat=excel
To: /content/migra.xls
100%|██████████| 166k/166k [00:00<00:00, 5.12MB/s]

migra.xls

In [10]:
df = pd.read_excel(filename)
df.head()

,Data Source,Indicadores del desarrollo mundial,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67
0,Last Updated Date,2024-05-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0
3,Aruba,ABW,Migración neta,SM.POP.NETM,0.0,-569.0,-609.0,-646.0,-684.0,-726.0,...,88.0,177.0,170.0,218.0,367.0,412.0,0.0,501.0,164.0,157.0
4,NaN,AFE,Migración neta,SM.POP.NETM,-90849.0,-1348.0,-24259.0,-16266.0,37452.0,11041.0,...,-199608.0,394925.0,-864708.0,-343075.0,-366105.0,-187410.0,-48955.0,-179444.0,-274282.0,-271749.0

In [16]:
df.iloc[0] #ACCEDEMOS AL INDICE 0

Data Source                             Last Updated Date
Indicadores del desarrollo mundial    2024-05-30 00:00:00
Unnamed: 2                                            NaN
Unnamed: 3                                            NaN
Unnamed: 4                                            NaN
                                             ...
Unnamed: 63                                           NaN
Unnamed: 64                                           NaN
Unnamed: 65                                           NaN
Unnamed: 66                                           NaN
Unnamed: 67                                           NaN
Name: 0, Length: 68, dtype: object

In [19]:
df.iloc[:,0] #MUESTA LA COLUMNA

0      Last Updated Date
1                    NaN
2           Country Name
3                  Aruba
4                    NaN
             ...
264               Kosovo
265      Yemen, Rep. del
266            Sudáfrica
267               Zambia
268             Zimbabwe
Name: Data Source, Length: 269, dtype: object

In [20]:
df.iloc[:5,0] #TODO HASTA LA FILA 5 Y COLUMNA 0

0    Last Updated Date
1                  NaN
2         Country Name
3                Aruba
4                  NaN
Name: Data Source, dtype: object